### ISSUE TITLE
Missing community guidelines

### ISSUE THREAD

**Issue by santisoler** [sinanozaydin/pide#11]
> [!NOTE]
> This issue was opened as part of the JOSS review process: https://github.com/openjournals/joss-reviews/issues/7021

## The issue

Currently `pide` lacks instructions on how to contribute to the repository and how to report issues. This is one of the JOSS requirements in order to accept the article for publication.

## Possible solution

I would suggest the authors to include community guidelines in the `README.md` and (optionally) in the documentation (see #9).

**Comment by sinanozaydin** [comment]
Contributing guidlines is added to the CONTRIBUTING.md, which has a link from README.md.

**Comment by santisoler** [comment]
Thanks @sinanozaydin for adding the contributing guidelines. They are greatly appreciated.
